name: Lint and Test

# Triggered by other workflows or on any push on branches
on:
  push:
    branches:
      - "**"
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        #os: [ubuntu-latest]
        #python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # lap package installation is unstable and requires numpy, and moreover it does not work with the default env set up by github...
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install wheel
          pip install numpy
          python -m pip install -r requirements-dev.txt
      - name: pylint
        run: |
          source env/bin/activate
          pylint pylapy
      - name: mypy
        run: |
          source env/bin/activate
          mypy pylapy
      - name: black
        run: |
          source env/bin/activate
          black --check .
      # TODO
      # - name: pytest
      #   run: |
      #     pytest